package com.placeToBeer.groupService.entities

import io.swagger.annotations.ApiModelProperty
import org.jetbrains.annotations.NotNull
import javax.persistence.*

@Entity
@Table(name = "friend_group")
data class Group(
        @Id
        @NotNull
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        @ApiModelProperty(
                value = "Autogenerated database id",
                example = "1",
                required = true)
        var id: Long,

        @NotNull
        @ApiModelProperty(
                value = "Name of the group",
                example = "Bratis Kartoffeln",
                required = true)
        var name: String) {

    constructor() : this(0, "")

}