package com.placeToBeer.groupService.entities

import io.swagger.annotations.ApiModelProperty
import org.jetbrains.annotations.NotNull
import javax.persistence.*

@Entity
@Table(name = "friend_group") //schema = "groups"
data class Group(
        @Id
        @NotNull
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        @ApiModelProperty(
                value = "Autogenerated database id",
                example = "1",
                required = true)
        var id: Long,

        @NotNull
        @ApiModelProperty(
                value = "Name of the group",
                example = "Bratis Kartoffeln",
                required = true)
        @Column(nullable = false)
        var name: String)
/*
        @OneToMany()
        @ApiModelProperty(
                value = "List of all memberships associated to this group",
                dataType = "List")
        var memberships: MutableList<Membership>)
*/  {
    constructor():this(0,""/*mutableListOf(Membership())*/) {
    }

}