package com.placeToBeer.groupService.entities

import com.placeToBeer.groupService.entities.requests.ProposalRequest
import io.swagger.annotations.ApiModelProperty
import org.hibernate.annotations.OnDelete
import org.hibernate.annotations.OnDeleteAction
import org.jetbrains.annotations.NotNull
import javax.persistence.*

@Entity
data class Proposal(
        @NotNull
        @Column(name = "proposal_name")
        @ApiModelProperty(
                value = "Name of the proposal",
                example = "Stövchen",
                required = true)
        var name: String,

        @NotNull
        @ManyToOne(cascade = [(CascadeType.MERGE)])
        @OnDelete(action = OnDeleteAction.CASCADE)
        @JoinColumn(name = "group_id")
        var group: Group,

        @NotNull
        @Column(name = "activity_type")
        var activityType: ActivityType
        ) {

    @Id
    @NotNull
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(
            value = "Autogenerated database id",
            example = "1",
            required = true)
    var id: Long? = null

    constructor() : this("", Group(), ActivityType.OTHER)

    constructor(proposalRequest: ProposalRequest, group: Group) : this(proposalRequest.name, group, proposalRequest.activityType)

}
